# Header
menu:
  Home: /
  Archives: /archives
  About: /about
  Projects: /projects

#rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics: UA-45866674-5
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
