# Header
logo_text: # Add text logo instead of logo image
menu:
  Home: /
  Archives: archives
  Categories: categories
  Tags: tags
  About: about

# Content
excerpt_link: Read More
fancybox: true

# Miscellaneous
google_analytics: UA-45866674-5
favicon: /favicon.png

